export const mockArr = [
  {
    diveNumber: 1,
    diveSite: "Thailand",
    date: "Dec 1",
    depth: 18,
    time: "1 hr",
    air: 70,
    weights: 4,
    visibility: 1,
    temperature: 20,
    activities: "shipwreck",
    kindOfDive: "Boat, saltwater",
    notes: "saw a mataray!",
  },

  {
    diveNumber: 2,
    diveSite: "Fiji",
    date: "Dec 31",
    depth: 30,
    time: "45 min",
    air: 65,
    weights: 4,
    visibility: 2,
    temperature: 23,
    activities: "reef",
    kindOfDive: "Boat, saltwater, night",
    notes: "turtles!",
  },
];
